image: python:latest

cache:
    paths:
        - ~/.cache/pip/

before_script:
    - python -V
    - apt-get update
    - apt-get install ssh-client

stages:
    - deploy

upload_to_server:
  stage: deploy
  before_script:
      - apt-get install -qq git
      - 'which ssh-agent || ( apt-get install -qq openssh-client )'
      - eval $(ssh-agent -s)
      - ssh-add <(echo "$SSH_PRIVATE_KEY")
      - mkdir -p ~/.ssh
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
      - ssh $SSH_USER@$SSH_HOST "cd prodserver_conf/ms104_market && git checkout master && git pull origin master && exit"
      - ssh $SSH_USER@$SSH_HOST "cd prodserver_conf && docker stop ms104_market && docker rm ms104_market && docker-compose build ms104_market && docker-compose up -d ms104_market && exit"
  only:
      - master