# Generated by Django 2.2.10 on 2020-04-05 18:12

from django.db import migrations
import oscar.models.fields.slugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20200316_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='slug',
            field=oscar.models.fields.slugfield.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
